# Generated by Django 3.2 on 2024-02-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('search_keyword', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('video_meta_data', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
