# Generated by Django 3.2 on 2024-02-26 13:30

from django.db import migrations, models
import drowsiness_detection.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recordingfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=drowsiness_detection.core.utils.FilenameForPathGenerator('recording_file')),
        ),
    ]
