# Generated by Django 3.2 on 2024-03-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20240226_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='google_drive_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
