# Generated by Django 3.2 on 2024-03-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_recordingfile_google_drive_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'File'), (2, 'Camera IP')], null=True),
        ),
    ]
