# Generated by Django 3.2 on 2024-03-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_recordingfile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingfile',
            name='google_drive_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
