# Generated by Django 3.2 on 2024-03-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_recordingfile_google_drive_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingfile',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'File'), (2, 'Camera IP')], default=1),
        ),
    ]
