# Generated by Django 3.2 on 2024-03-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_recordingfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='isFromGoogleDrive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordingfile',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'File'), (2, 'Live Streaming\xa0')], default=1),
        ),
    ]
