# Generated by Django 3.2 on 2024-03-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20240304_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recordingfile',
            old_name='isFromGoogleDrive',
            new_name='is_from_gdrive',
        ),
    ]
