# Generated by Django 3.2 on 2024-03-06 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drowsiness_detection.core.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0009_rename_isfromgoogledrive_recordingfile_is_from_gdrive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=drowsiness_detection.core.utils.FilenameForPathGenerator('recording_file'))),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_image', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_image', to=settings.AUTH_USER_MODEL)),
                ('recording_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_image', to='files.recordingfile')),
            ],
        ),
    ]
