# Generated by Django 3.2 on 2024-03-08 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
        ('files', '0010_imagesfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesfile',
            name='recording_file',
        ),
        migrations.AddField(
            model_name='imagesfile',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_image_file', to='cameras.camera'),
        ),
        migrations.AddField(
            model_name='recordingfile',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_recording_file', to='cameras.camera'),
        ),
        migrations.AlterField(
            model_name='recordingfile',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'File'), (2, 'Live Streaming')], default=1),
        ),
    ]
