# Generated by Django 3.2 on 2024-03-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_auto_20240308_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordingfile',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'File'), (2, 'Live Streaming'), (3, 'Google Drive')], default=1),
        ),
    ]
