# Generated by Django 3.2 on 2024-03-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20240310_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordingfile',
            name='mimetype',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Video'), (2, 'Image'), (3, 'ZIP')], null=True),
        ),
    ]
