# Generated by Django 3.2 on 2024-02-27 05:13

from django.db import migrations, models
import drowsiness_detection.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=drowsiness_detection.core.utils.FilenameForPathGenerator('user_image')),
        ),
    ]
