# Generated by Django 3.2 on 2024-03-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAuthGDrive',
            field=models.BooleanField(default=False),
        ),
    ]
