"""
Django settings for drowsiness_detection project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os

from os import path
from os.path import abspath, dirname, join
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# Absolute filesystem path to the directory that will hold user-uploaded files.
# Example: "/home/media/media.lawrence.com/media/"
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = path.dirname(__file__)
DJANGO_ROOT = dirname(abspath(__file__))
PROJECT_ROOT = path.dirname(SETTINGS_DIR)
STATIC_ROOT = join(PROJECT_ROOT, 'static')

STATIC_URL = '/static/'
STATIC_ROOT = join(DJANGO_ROOT, 'static')
STATICFILES_DIRS = (
    path.join(PROJECT_ROOT, 'static'),
)

MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'

CONFIG_ROOT = os.path.join(PROJECT_ROOT, 'config')
GOOGLE_DRIVE_CONFIG_ROOT = os.path.join(CONFIG_ROOT, 'google_drive')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vyh3r*j!)dtz$xed(ow(6kdfcva!mw@sbs(^og=h((i5qv+iv%'

AUTH_USER_MODEL = 'users.User'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool) 
# DEBUG = False # For production

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'drowsiness_detection.apps.cameras',
    'drowsiness_detection.apps.files',
    'drowsiness_detection.apps.users',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    'fontawesomefree'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware'
]

ROOT_URLCONF = 'drowsiness_detection.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            path.join(DJANGO_ROOT, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'querystring': 'libraries.utils.templatetags.querystring',
                'static_files': 'libraries.utils.templatetags.static_files'
            }
        },
    },
]

WSGI_APPLICATION = 'drowsiness_detection.wsgi.application'
LOGIN_URL = '/auth/login'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    
    # Uncomment if using postgresql
    # Use OPTIONS if you want in spesific schemas
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME', default='postgres'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': 5432,
    },
    
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', )
}

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
LANGUAGES = (
    ('en', 'English'),
    ('id', 'Indonesian'),
)

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_TZ = True

COUNTRY = 'ID'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH FOR TWILIO
TWILIO_SID = config('TWILIO_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WA_NUMBER = config('TWILIO_WA_NUMBER', default='+14155238886')

#GOOGLE DRIVE AUTH
API_NAME = config('API_NAME', default='')
API_VERSION = config('API_VERSION', default='')
CLIENT_SECRET_FILE = os.path.join(GOOGLE_DRIVE_CONFIG_ROOT, config('CLIENT_SECRET_FILE', default=''))
CLIENT_SECRET_PROD = os.path.join(GOOGLE_DRIVE_CONFIG_ROOT, config('CLIENT_SECRET_PROD', default=''))

REFRESH_MONITOR_PAGE = config('REFRESH_MONITOR_PAGE', default=0, cast=int)
ENV = config('ENV', default='LOCAL')